# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\"V\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x14\n\x0cis_available\x18\x05 \x01(\x08\"\"\n\x0b\x42ookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"4\n\x0c\x42ookResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.Book\"1\n\rBorrowRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"/\n\x0c\x42orrowStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest2\xd4\x01\n\x0eLibraryService\x12(\n\x07\x41\x64\x64\x42ook\x12\x0c.BookRequest\x1a\r.BookResponse\"\x00\x12\x36\n\x12ListAvailableBooks\x12\r.EmptyRequest\x1a\r.BookResponse\"\x00\x30\x01\x12\x30\n\x0b\x42orrowBooks\x12\x0e.BorrowRequest\x1a\r.BorrowStatus\"\x00(\x01\x12.\n\x0fLiveBookUpdates\x12\x0e.BorrowRequest\x1a\x05.Book\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=17
  _globals['_BOOK']._serialized_end=103
  _globals['_BOOKREQUEST']._serialized_start=105
  _globals['_BOOKREQUEST']._serialized_end=139
  _globals['_BOOKRESPONSE']._serialized_start=141
  _globals['_BOOKRESPONSE']._serialized_end=193
  _globals['_BORROWREQUEST']._serialized_start=195
  _globals['_BORROWREQUEST']._serialized_end=244
  _globals['_BORROWSTATUS']._serialized_start=246
  _globals['_BORROWSTATUS']._serialized_end=293
  _globals['_EMPTYREQUEST']._serialized_start=295
  _globals['_EMPTYREQUEST']._serialized_end=309
  _globals['_LIBRARYSERVICE']._serialized_start=312
  _globals['_LIBRARYSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
