# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """The library service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBook = channel.unary_unary(
                '/LibraryService/AddBook',
                request_serializer=library__pb2.BookRequest.SerializeToString,
                response_deserializer=library__pb2.BookResponse.FromString,
                _registered_method=True)
        self.ListAvailableBooks = channel.unary_stream(
                '/LibraryService/ListAvailableBooks',
                request_serializer=library__pb2.EmptyRequest.SerializeToString,
                response_deserializer=library__pb2.BookResponse.FromString,
                _registered_method=True)
        self.BorrowBooks = channel.stream_unary(
                '/LibraryService/BorrowBooks',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.BorrowStatus.FromString,
                _registered_method=True)
        self.LiveBookUpdates = channel.stream_stream(
                '/LibraryService/LiveBookUpdates',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """The library service definition.
    """

    def AddBook(self, request, context):
        """unary RPCs: The client sends a single request to the server and gets a single response back, just like a normal function call.
        sends book request and get details as book response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableBooks(self, request, context):
        """server streaming RPCs: sends empty request and response as stream available of list of books.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBooks(self, request_iterator, context):
        """client streaming RPCs: sends stream of the borrow request request and response as the borrow status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveBookUpdates(self, request_iterator, context):
        """bidirectional streaming RPCs: sends stream of borrow request and response of stream book response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=library__pb2.BookRequest.FromString,
                    response_serializer=library__pb2.BookResponse.SerializeToString,
            ),
            'ListAvailableBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAvailableBooks,
                    request_deserializer=library__pb2.EmptyRequest.FromString,
                    response_serializer=library__pb2.BookResponse.SerializeToString,
            ),
            'BorrowBooks': grpc.stream_unary_rpc_method_handler(
                    servicer.BorrowBooks,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.BorrowStatus.SerializeToString,
            ),
            'LiveBookUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveBookUpdates,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """The library service definition.
    """

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LibraryService/AddBook',
            library__pb2.BookRequest.SerializeToString,
            library__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/LibraryService/ListAvailableBooks',
            library__pb2.EmptyRequest.SerializeToString,
            library__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBooks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/LibraryService/BorrowBooks',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.BorrowStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveBookUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/LibraryService/LiveBookUpdates',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
